from __future__ import annotations

import gc
import math
from pathlib import Path
from types import SimpleNamespace

import numpy as np
from PySide6.QtCore import QTimer
from PySide6.QtWidgets import QLabel, QVBoxLayout, QWidget

from app.runtime import VISUAL_ROCKET_MODEL_STL, application_root
from app.services.cfd_geometry import PHYSICAL_BODY_LENGTH_M


# Labels and swatches used by the color-filter checkboxes in the CFD tab.
DISPLAY_LAYERS = {
    "flow": ("Flujo de velocidad", "#28c9ff", "azul → rojo"),
    "vortices": ("Vórtices", "#cf35f4", "morado → amarillo"),
    "particles": ("Partículas de aire", "#ff9f1c", "naranja"),
    "rain": ("Lluvia", "#41e7ff", "cian"),
    "drag": ("Arrastre", "#ff3b30", "rojo"),
    "lift": ("Sustentación", "#47ff78", "verde"),
    "side": ("Fuerza lateral", "#39a8ff", "azul"),
    "friction": ("Fricción", "#ff9f1c", "naranja"),
    "cfd_field": ("Presión sobre cohete", "#ffdd33", "Pa · superficie"),
}

# A layer may only be rendered when its named source array exists in the VTK
# output generated by OpenFOAM.  The labels are used verbatim in the legend.
CFD_FIELD_LAYERS = {
    "velocity": ("Velocidad", "U", "m/s", "turbo"),
    "pressure": ("Presión", "p", "Pa", "coolwarm"),
    "vorticity": ("Vorticidad", "vorticity", "1/s", "plasma"),
    "turbulence": ("Intensidad turbulenta", "k", "%", "turbo"),
}

CFD_VISUAL_MODES = {
    "velocity": ("Velocidad del flujo", "m/s"),
    "pressure": ("Presión sobre el cohete", "Pa"),
    "vorticity": ("Vorticidad", "1/s"),
    "turbulence": ("Intensidad turbulenta", "%"),
    "drag": ("Arrastre", "N"),
    "lift": ("Sustentación", "N"),
    "side": ("Fuerza lateral", "N"),
    "friction": ("Fricción viscosa", "N"),
    "moment": ("Momento aerodinámico", "N·m"),
}


def _frame_value(frame: object, name: str, default: object = None) -> object:
    """Read both current CfdFrame objects and manifests from older runs."""
    if isinstance(frame, dict):
        return frame.get(name, default)
    return getattr(frame, name, default)


def _normalise_cfd_frame(frame: object) -> object:
    """Adapt legacy JSON frame dictionaries before rendering them."""
    if not isinstance(frame, dict):
        return frame
    vtk_path = frame.get("vtk_path")
    surface_path = frame.get("surface_vtk_path")
    return SimpleNamespace(
        time_s=float(frame.get("time_s", 0.0)),
        canard_deg=tuple(float(value) for value in frame.get("canard_deg", (0.0, 0.0, 0.0, 0.0))),
        vtk_path=Path(vtk_path) if vtk_path else None,
        surface_vtk_path=Path(surface_path) if surface_path else None,
        force_n=tuple(float(value) for value in frame.get("force_n", (0.0, 0.0, 0.0))),
        moment_nm=tuple(float(value) for value in frame.get("moment_nm", (0.0, 0.0, 0.0))),
        pressure_force_n=frame.get("pressure_force_n"),
        viscous_force_n=frame.get("viscous_force_n"),
        inlet_velocity_body_mps=tuple(float(value) for value in frame.get("inlet_velocity_body_mps", (1.0, 0.0, 0.0))),
        recovery_force_n=tuple(float(value) for value in frame.get("recovery_force_n", (0.0, 0.0, 0.0))),
        center_of_gravity_body_m=tuple(float(value) for value in frame.get("center_of_gravity_body_m", (0.0, 0.0, 0.0))),
    )


def flow_direction(alpha_deg: float, beta_deg: float) -> np.ndarray:
    """Return +X tunnel flow; alpha is +Z and beta is +Y by convention."""
    alpha, beta = np.radians(alpha_deg), np.radians(beta_deg)
    direction = np.array((np.cos(alpha) * np.cos(beta), np.sin(beta), np.sin(alpha)), dtype=float)
    return direction / max(float(np.linalg.norm(direction)), 1e-9)


def aerodynamic_force_vectors(force_n: object, inlet_velocity_body_mps: object) -> dict[str, np.ndarray]:
    """Project one integrated load into drag, side and lift relative to U∞."""
    force = np.asarray(force_n, dtype=float).reshape(3)
    inlet = np.asarray(inlet_velocity_body_mps, dtype=float).reshape(3)
    speed = float(np.linalg.norm(inlet))
    if speed <= 1e-12:
        drag_axis = np.array((-1.0, 0.0, 0.0))
    else:
        drag_axis = inlet / speed
    body_up = np.array((0.0, 0.0, 1.0))
    lift_axis = body_up - float(np.dot(body_up, drag_axis)) * drag_axis
    if float(np.linalg.norm(lift_axis)) <= 1e-8:
        body_up = np.array((0.0, 1.0, 0.0))
        lift_axis = body_up - float(np.dot(body_up, drag_axis)) * drag_axis
    lift_axis /= max(float(np.linalg.norm(lift_axis)), 1e-12)
    side_axis = np.cross(drag_axis, lift_axis)
    side_axis /= max(float(np.linalg.norm(side_axis)), 1e-12)
    lift_axis = np.cross(side_axis, drag_axis)
    lift_axis /= max(float(np.linalg.norm(lift_axis)), 1e-12)
    return {
        "drag": float(np.dot(force, drag_axis)) * drag_axis,
        "side": float(np.dot(force, side_axis)) * side_axis,
        "lift": float(np.dot(force, lift_axis)) * lift_axis,
    }


def robust_scalar_range(
    values: object, *, symmetric: bool = False, lower: float = 2.0, upper: float = 98.0,
) -> tuple[float, float]:
    """Return a finite CFD colour range that is not dominated by a few outliers."""
    finite = np.asarray(values, dtype=float).reshape(-1)
    finite = finite[np.isfinite(finite)]
    if not finite.size:
        return (-1.0, 1.0) if symmetric else (0.0, 1.0)
    low, high = (float(value) for value in np.nanpercentile(finite, (lower, upper)))
    if symmetric:
        limit = max(abs(low), abs(high), np.finfo(float).eps)
        return -limit, limit
    if high <= low:
        padding = max(abs(high) * 0.05, 1e-9)
        return low - padding, high + padding
    return low, high


def aerodynamic_metrics(
    speed_mps: float, alpha_deg: float, beta_deg: float, canards_deg: tuple[float, float, float, float],
    rain_rate_mm_h: float,
) -> dict[str, float]:
    """Small transparent engineering model used to label the live visualization."""
    rho, area = 1.225, 0.002027
    q = 0.5 * rho * max(speed_mps, 0.0) ** 2
    alpha, beta = math.radians(alpha_deg), math.radians(beta_deg)
    canard_rms = math.sqrt(sum(value * value for value in canards_deg) / 4.0)
    rain_factor = 1.0 + min(0.15, max(0.0, rain_rate_mm_h) * 0.01)
    drag = q * area * (0.55 + 0.8 * alpha * alpha) * rain_factor
    lift = q * area * (2.0 * abs(alpha) + 0.035 * math.radians(canard_rms))
    side = q * area * 1.6 * abs(beta)
    friction = q * area * (0.018 + 0.002 * max(speed_mps, 0.0) / 30.0)
    vorticity = max(speed_mps, 0.0) * (0.18 + 0.045 * canard_rms)
    return {
        "dynamic_pressure_pa": q,
        "drag_n": drag,
        "lift_n": lift,
        "side_n": side,
        "friction_n": friction,
        "vorticity_s": vorticity,
    }


class CfdViewport(QWidget):
    """Wind-tunnel viewport with an illustrative preview and VTK-only CFD layers.

    Coordinates are fixed across the UI, exported STL and OpenFOAM case: +X is
    nose/longitudinal, +Y is starboard/right and +Z is top. Positive alpha
    tilts the inlet towards +Z and positive beta towards +Y.
    """

    # Legacy OBJ group order mapped to the labels shown in the PID table:
    # C1 superior (+X), C2 derecha (+Y), C3 inferior (-X), C4 izquierda (-Y).
    # Groups 3–6 are the white fixed guide/support surfaces; the orange
    # articulated canards in the model are groups 10–13.
    _CANARD_GROUPS = (10, 13, 12, 11)
    _FIXED_GROUPS = (0, 1, 2, 3, 4, 5, 6, 7, 8, 9)
    _FIXED_COLORS = {
        0: "#eef4f7", 1: "#dd642b", 2: "#087da8",
        3: "#285f78", 4: "#eef4f7", 5: "#eef4f7", 6: "#eef4f7",
        7: "#f5a623", 8: "#0b6f97", 9: "#dd642b",
    }
    _CANARD_COLORS = ("#ff9f1c", "#ff7a00", "#ffb000", "#f97316")
    # Render the physical PID angle exactly without leaving a ghost/reference
    # fin at its original position.
    _CANARD_VISUAL_GAIN = 1.0
    _CANARD_VISUAL_LIMIT_DEG = 90.0
    _FLOW_VIEW_BOUNDS = (-1.20, 1.20, -0.44, 0.44, -0.44, 0.44)

    @staticmethod
    def _stl_components(mesh: object) -> tuple[list[object], tuple[object, object, object, object]] | None:
        """Split the supplied STL into fixed pieces and its four radial canards.

        The supplied NACA 661-212 assembly has no OBJ group labels, but it
        preserves the canards as four disconnected radial components. Identify
        them from their centre location rather than depending on OBJ groups.
        """
        try:
            connected = mesh.connectivity("all", label_regions=True)
            region_ids = np.asarray(connected.cell_data["RegionId"])
            pieces = [
                connected.extract_cells(np.flatnonzero(region_ids == region)).extract_surface(algorithm="dataset_surface")
                for region in np.unique(region_ids)
            ]
            radial_extent = max(float(mesh.bounds[1] - mesh.bounds[0]), float(mesh.bounds[3] - mesh.bounds[2]), 1e-9)
            centre = np.asarray(mesh.center, dtype=float)
            candidates = [
                piece for piece in pieces
                if np.linalg.norm(np.asarray(piece.center, dtype=float)[:2] - centre[:2]) > 0.20 * radial_extent
            ]
            if len(candidates) != 4:
                return None
            c1 = max(candidates, key=lambda piece: float(piece.center[0]))
            c2 = max(candidates, key=lambda piece: float(piece.center[1]))
            c3 = min(candidates, key=lambda piece: float(piece.center[0]))
            c4 = min(candidates, key=lambda piece: float(piece.center[1]))
            canards = (c1, c2, c3, c4)
            if len({id(piece) for piece in canards}) != 4:
                return None
            return [piece for piece in pieces if all(piece is not canard for canard in canards)], canards
        except (KeyError, TypeError, ValueError):
            return None

    def __init__(self, parent: QWidget | None = None) -> None:
        super().__init__(parent)
        self._pv = self._plotter = None
        self._render_enabled = False
        self._widget_visible = False
        self._closed = False
        self._render_pending = False
        self._center = np.zeros(3)
        self._length = 1.0
        self._canard_actors: list[object] = []
        self._canard_meshes: list[object] = []
        self._flow_names: list[str] = []
        self._streamline_names: list[str] = []
        self._vortex_names: list[str] = []
        self._force_names: list[str] = []
        self._force_actor_names: dict[str, str] = {}
        self._force_metrics: dict[str, float] = {}
        self._layer_visibility = {key: True for key in DISPLAY_LAYERS}
        self._flow_paths: list[np.ndarray] = []
        self._vortex_meshes: list[object] = []
        self._vortex_actors: list[object] = []
        self._particle_mesh = None
        self._rain_mesh = None
        self._particle_phase = 0.0
        self._preview_names: list[str] = []
        self._cfd_dataset = None
        self._cfd_result = None
        self._cfd_frames: tuple[object, ...] = ()
        self._cfd_frame_index: int | None = None
        self._cfd_available_fields: dict[str, str] = {}
        self._cfd_layer = "velocity"
        self._following_rocket = False
        self._flow_key: tuple[float, float, float, float] | None = None
        self._force_key: tuple[float, ...] | None = None
        self._speed_mps = 0.0
        self._alpha_deg = 0.0
        self._beta_deg = 0.0
        self._canards = (0.0, 0.0, 0.0, 0.0)
        self._rain_rate_mm_h = 0.0
        self._wind_enu_mps = (0.0, 0.0, 0.0)
        self._weather_source = "perfil local"
        self._temperature_k = 288.15
        self._pressure_pa = 101325.0
        self._humidity_ratio = 0.0
        layout = QVBoxLayout(self)
        layout.setContentsMargins(0, 0, 0, 0)
        try:
            import pyvista as pv
            from pyvistaqt import QtInteractor

            self._pv = pv
            # Disable pyvistaqt's own five-Hz timer.  The laboratory has a
            # controlled animation timer which is paused with the tab, so an
            # invisible widget never renders into an invalid Windows WGL context.
            self._plotter = QtInteractor(self, auto_update=False)
            self._plotter.suppress_rendering = True
            self._plotter.set_background("#eef3f7", top="#ffffff")
            self._plotter.enable_trackball_style()
            try:
                # Correct transparent ordering is essential when dense vector
                # glyphs, a vortex envelope and stream tubes overlap.
                self._plotter.enable_depth_peeling()
            except (RuntimeError, TypeError):
                pass
            self._plotter.add_axes(line_width=2)
            layout.addWidget(self._plotter.interactor)
            self._load_model()
            self._flow_timer = QTimer(self)
            self._flow_timer.setInterval(1000 // 30)
            self._flow_timer.timeout.connect(self._animate_flow)
        except ImportError:
            fallback = QLabel("El laboratorio CFD necesita PyVista/VTK. Ejecuta python run_all.py --launch.")
            fallback.setWordWrap(True)
            layout.addWidget(fallback)

    def set_rendering_enabled(self, enabled: bool) -> None:
        """Enable the native renderer only for the currently visible tab."""
        self._render_enabled = bool(enabled) and not self._closed
        self._sync_render_state()
        if self._render_enabled and self._widget_visible:
            self._render_scene()

    def showEvent(self, event: object) -> None:
        self._widget_visible = True
        self._sync_render_state()
        super().showEvent(event)
        if self._render_enabled:
            QTimer.singleShot(0, self._render_scene)

    def hideEvent(self, event: object) -> None:
        self._widget_visible = False
        self._sync_render_state()
        super().hideEvent(event)

    def _sync_render_state(self) -> None:
        active = self._render_enabled and self._widget_visible and not self._closed
        if self._plotter is not None:
            self._plotter.suppress_rendering = not active
        timer = getattr(self, "_flow_timer", None)
        if timer is not None:
            if active:
                timer.start()
            else:
                timer.stop()

    def _render_scene(self) -> None:
        if (
            self._plotter is None
            or getattr(self, "_closed", False)
            or not getattr(self, "_render_enabled", True)
            or not getattr(self, "_widget_visible", True)
        ):
            self._render_pending = True
            return
        self._plotter.suppress_rendering = False
        try:
            self._plotter.render()
            self._render_pending = False
        except RuntimeError:
            self._render_pending = True

    def shutdown(self) -> None:
        """Release timers and the VTK render window before Qt tears down tabs."""
        if self._closed:
            return
        self._closed = True
        self._render_enabled = False
        self._widget_visible = False
        timer = getattr(self, "_flow_timer", None)
        if timer is not None:
            timer.stop()
        if self._plotter is not None:
            self._plotter.suppress_rendering = True
            try:
                self._plotter.close()
            except RuntimeError:
                pass
            self._plotter = None

    def _load_model(self) -> None:
        if not self._pv or not self._plotter:
            return
        path = application_root() / "data" / "models" / VISUAL_ROCKET_MODEL_STL
        if not path.is_file():
            return
        mesh = self._pv.read(path)
        groups = mesh.cell_data.get("GroupIds")
        self._center = np.asarray(mesh.center, dtype=float)
        self._length = max(float(mesh.bounds[5] - mesh.bounds[4]), 1e-6)
        scale_matrix = np.eye(4)
        # Source model is longitudinal +Z; rotate it once to the shared +X
        # OpenFOAM/viewport convention used by the tunnel and exported STL.
        scale_matrix[:3, :3] = np.array(((0.0, 0.0, 1.0), (0.0, 1.0, 0.0), (-1.0, 0.0, 0.0))) * (PHYSICAL_BODY_LENGTH_M / self._length)
        if groups is None:
            split = self._stl_components(mesh)
            if split is None:
                self._plotter.add_mesh(mesh, color="#d8e6ee", smooth_shading=True)
                return
            fixed_pieces, canard_pieces = split
            # The STL has no material groups.  Give the major fixed pieces a
            # coherent livery, without drawing every triangle edge as a brown
            # wireframe over the body.
            stl_colors = ("#eef4f7", "#087da8", "#dd642b", "#285f78")
            fixed_entries = [
                (piece, stl_colors[index % len(stl_colors)], False)
                for index, piece in enumerate(fixed_pieces)
            ]
        else:
            fixed_entries = [
                (mesh.extract_cells(np.flatnonzero(groups == group)), self._FIXED_COLORS.get(group, "#dce8ef"), False)
                for group in self._FIXED_GROUPS
            ]
            canard_pieces = tuple(mesh.extract_cells(np.flatnonzero(groups == group)) for group in self._CANARD_GROUPS)
        for index, (piece, color, show_edges) in enumerate(fixed_entries):
            if piece.n_cells == 0:
                continue
            local_piece = piece.copy(deep=True); local_piece.translate(-self._center, inplace=True)
            actor = self._plotter.add_mesh(
                local_piece, color=color, smooth_shading=True,
                metallic=0.32, roughness=0.26, show_edges=show_edges,
                scalars=None, show_scalar_bar=False,
                name=f"rocket-fixed-{index}",
            )
            actor.user_matrix = scale_matrix
        for index, piece in enumerate(canard_pieces):
            if piece.n_cells == 0:
                continue
            local_piece = piece.copy(deep=True); local_piece.translate(-self._center, inplace=True)
            self._canard_meshes.append(local_piece)
            actor = self._plotter.add_mesh(
                local_piece, color=self._CANARD_COLORS[index], smooth_shading=True, show_edges=False,
                metallic=0.30, roughness=0.18, ambient=0.55,
                scalars=None, show_scalar_bar=False, name=f"pid-canard-{index}",
            )
            self._canard_actors.append(actor)
        tunnel = self._pv.Box(bounds=(-2.0, 2.0, -1.6, 1.6, -1.6, 1.6))
        self._plotter.add_mesh(
            tunnel, style="wireframe", color="#8fa5b5", opacity=0.20, line_width=1,
            name="wind-tunnel", reset_camera=False,
        )
        self.set_conditions(25.0, 0.0, 0.0, (0.0, 0.0, 0.0, 0.0), 0.0)
        self.set_camera_preset("isometric")

    def set_model_path(self, path: str | Path) -> None:
        """Preview a user-selected CFD STL without treating it as mass data."""
        candidate = Path(path).expanduser()
        if candidate.suffix.lower() != ".stl" or not candidate.is_file():
            raise ValueError("Selecciona un archivo STL existente")
        if not self._pv or not self._plotter:
            return
        mesh = self._pv.read(candidate)
        if mesh.n_points < 3 or mesh.n_cells < 1:
            raise ValueError("El STL está vacío")
        mesh = mesh.extract_surface().triangulate().clean()
        if int(getattr(mesh, "n_open_edges", 0)) > 0:
            raise ValueError("El STL no es una superficie cerrada; corrige sus bordes abiertos antes de usar OpenFOAM")
        bounds = tuple(float(value) for value in mesh.bounds)
        extents = np.array((bounds[1] - bounds[0], bounds[3] - bounds[2], bounds[5] - bounds[4]))
        longitudinal_axis = int(np.argmax(extents))
        source_length = float(extents[longitudinal_axis])
        if source_length <= 1e-9:
            raise ValueError("El STL no tiene una dimensión longitudinal positiva")
        # Map the longest source axis to the shared +X tunnel convention.  The
        # preview is scaled for comparison; the original file remains intact
        # and is copied verbatim into the auditable OpenFOAM case.
        rotation = np.zeros((3, 3))
        rotation[0, longitudinal_axis] = 1.0
        remaining = [axis for axis in range(3) if axis != longitudinal_axis]
        rotation[1, remaining[0]] = 1.0
        rotation[2, remaining[1]] = 1.0
        scale = PHYSICAL_BODY_LENGTH_M / source_length
        transform = np.eye(4); transform[:3, :3] = rotation * scale
        local = mesh.copy(deep=True); local.translate(-np.asarray(mesh.center, dtype=float), inplace=True)
        self._plotter.clear()
        self._canard_actors.clear(); self._canard_meshes.clear()
        self._center = np.zeros(3); self._length = PHYSICAL_BODY_LENGTH_M
        actor = self._plotter.add_mesh(
            local, color="#d8e6ee", smooth_shading=True, metallic=0.25, roughness=0.30,
            name="custom-cfd-rocket", reset_camera=False,
        )
        actor.user_matrix = transform
        tunnel = self._pv.Box(bounds=(-2.0, 2.0, -1.6, 1.6, -1.6, 1.6))
        self._plotter.add_mesh(tunnel, style="wireframe", color="#8fa5b5", opacity=0.20, line_width=1, name="wind-tunnel", reset_camera=False)
        self._flow_key = None; self._force_key = None
        self.set_conditions(self._speed_mps, self._alpha_deg, self._beta_deg, self._canards, self._rain_rate_mm_h)
        self.set_camera_preset("isometric")

    @staticmethod
    def _rotate(axis: np.ndarray, radians: float) -> np.ndarray:
        axis = axis / max(float(np.linalg.norm(axis)), 1e-9)
        skew = np.array(((0.0, -axis[2], axis[1]), (axis[2], 0.0, -axis[0]), (-axis[1], axis[0], 0.0)))
        return np.eye(3) + np.sin(radians) * skew + (1.0 - np.cos(radians)) * (skew @ skew)

    def _canard_transform(self, index: int, degrees: float) -> np.ndarray:
        mesh = self._canard_meshes[index]
        pivot = self._canard_hinge_pivot(index, mesh.bounds)
        # Rotate around each canard's radial servo axle. Using outward-facing
        # axes preserves the sign convention of each independent PID command.
        axes = (
            np.array((1.0, 0.0, 0.0)),   # C1, +X
            np.array((0.0, 1.0, 0.0)),   # C2, +Y
            np.array((-1.0, 0.0, 0.0)),  # C3, -X
            np.array((0.0, -1.0, 0.0)),  # C4, -Y
        )
        rotation = self._rotate(axes[index], np.radians(degrees))
        local = np.eye(4)
        local[:3, :3] = rotation
        local[:3, 3] = pivot - rotation @ pivot
        scale = PHYSICAL_BODY_LENGTH_M / self._length
        world = np.eye(4)
        world[:3, :3] = np.array(((0.0, 0.0, 1.0), (0.0, 1.0, 0.0), (-1.0, 0.0, 0.0))) * scale
        return world @ local

    @classmethod
    def _visual_canard_angle(cls, pid_degrees: float) -> float:
        """Amplify the rendered motion only; PID and CFD retain the real angle."""
        return float(np.clip(
            float(pid_degrees) * cls._CANARD_VISUAL_GAIN,
            -cls._CANARD_VISUAL_LIMIT_DEG,
            cls._CANARD_VISUAL_LIMIT_DEG,
        ))

    @staticmethod
    def _canard_hinge_pivot(index: int, bounds: tuple[float, float, float, float, float, float]) -> np.ndarray:
        """Return the body-side hinge line, rather than the centre of the fin."""
        x_min, x_max, y_min, y_max, z_min, z_max = (float(value) for value in bounds)
        # The rounded/thick forward edge is the servo cylinder.  Its spanwise
        # axis is at z_max; that complete line must remain fixed while the
        # thinner trailing edge sweeps with the PID command.
        hinge_z = z_max
        if index == 0:   # C1 superior: +X fin, axle X
            return np.array((x_min, 0.5 * (y_min + y_max), hinge_z))
        if index == 1:   # C2 derecha: +Y fin, axle Y
            return np.array((0.5 * (x_min + x_max), y_min, hinge_z))
        if index == 2:   # C3 inferior: -X fin, axle -X
            return np.array((x_max, 0.5 * (y_min + y_max), hinge_z))
        if index == 3:   # C4 izquierda: -Y fin, axle -Y
            return np.array((0.5 * (x_min + x_max), y_max, hinge_z))
        raise ValueError(f"Índice de canard inválido: {index}")

    def set_weather_context(
        self, wind_enu_mps: tuple[float, float, float], temperature_k: float, pressure_pa: float,
        humidity_ratio: float, source: str,
    ) -> None:
        self._wind_enu_mps = tuple(float(value) for value in wind_enu_mps)
        self._temperature_k = float(temperature_k)
        self._pressure_pa = float(pressure_pa)
        self._humidity_ratio = float(humidity_ratio)
        self._weather_source = str(source)
        self._update_caption()

    def set_layer_visible(self, layer: str, visible: bool) -> None:
        """Show or hide a named colored CFD layer without rebuilding the scene."""
        if layer not in self._layer_visibility:
            raise ValueError(f"Capa CFD desconocida: {layer}")
        self._layer_visibility[layer] = bool(visible)
        self._apply_layer_visibility()
        if self._plotter:
            self._render_scene()

    def layer_visible(self, layer: str) -> bool:
        return bool(self._layer_visibility.get(layer, False))

    def set_conditions(
        self, speed_mps: float, alpha_deg: float, beta_deg: float,
        canards: tuple[float, float, float, float], rain_rate_mm_h: float,
    ) -> None:
        if not self._plotter or not self._pv:
            return
        self._speed_mps = float(speed_mps)
        self._alpha_deg = float(alpha_deg)
        self._beta_deg = float(beta_deg)
        self._canards = tuple(float(value) for value in canards)
        self._rain_rate_mm_h = float(rain_rate_mm_h)
        self._plotter.set_background("#eef3f7", top="#ffffff")
        for index, (actor, angle) in enumerate(zip(self._canard_actors, self._canards)):
            actor.user_matrix = self._canard_transform(index, self._visual_canard_angle(angle))
        # A change to the preview invalidates every previous CFD result. This
        # also removes actors created by older versions of the viewport so a
        # local preliminary fallback can never look like a detailed result.
        self._clear_result_actors()
        # The preview deliberately has no synthetic loads, streamlines or
        # vortices. Those are only created below from an OpenFOAM VTK field.
        self._build_preview_illustration()
        self._update_caption()
        self._render_scene()

    def set_canard_deflections(self, canards: tuple[float, float, float, float]) -> None:
        """Replay PID motion without replacing an already loaded CFD result."""
        if not self._plotter:
            return
        self._canards = tuple(float(value) for value in canards)
        for index, (actor, angle) in enumerate(zip(self._canard_actors, self._canards)):
            actor.user_matrix = self._canard_transform(index, self._visual_canard_angle(angle))
        self._maintain_follow_camera()
        self._render_scene()

    def _clear_result_actors(self) -> None:
        """Remove CFD and legacy estimated actors without touching the rocket."""
        if not self._plotter:
            return
        names = {
            *self._flow_names, *self._streamline_names, *self._vortex_names, *self._force_names,
            *self._force_actor_names.values(),
            "flow-particles", "rain-particles", "cfd-streamlines", "cfd-velocity-glyphs",
            "cfd-velocity-plane", "cfd-pressure-surface", "cfd-vorticity-surface",
            "cfd-vorticity-lines", "cfd-vortex-rings", "cfd-vortex-ring-arrows", "cfd-turbulence-lines",
            "cfd-wall-shear", "cfd-wall-shear-surface", "cfd-wall-shear-contours",
            "cfd-moment", "cfd-moment-tip",
            "cfd-moment-axis", "force-legend", "cfd-mode-info", "preview-notice", "cfd-caption",
            "cfd-result",
        }
        for name in names:
            self._plotter.remove_actor(name, render=False)
        self._flow_names.clear(); self._streamline_names.clear(); self._vortex_names.clear()
        self._force_names.clear(); self._force_actor_names.clear(); self._force_metrics.clear()
        self._flow_paths.clear(); self._vortex_meshes.clear(); self._vortex_actors.clear()
        self._particle_mesh = None; self._rain_mesh = None; self._cfd_dataset = None; self._cfd_result = None
        self._cfd_frames = (); self._cfd_frame_index = None
        self._cfd_available_fields.clear()
        for title in (
            "Velocidad (m/s)", "Vorticidad (1/s)", "Intensidad turbulenta (%)",
            "Presión manométrica (Pa)", "Esfuerzo cortante (Pa)",
        ):
            try:
                self._plotter.remove_scalar_bar(title, render=False)
            except (KeyError, ValueError):
                pass
        gc.collect()

    def _build_preview_illustration(self) -> None:
        """Render the non-physical preview aids, clearly labelled as such."""
        if not self._plotter or not self._pv:
            return
        for name in self._preview_names:
            self._plotter.remove_actor(name, render=False)
        self._preview_names.clear()
        direction = flow_direction(self._alpha_deg, self._beta_deg)
        arrow = self._pv.Arrow(start=-direction * 1.75, direction=direction, scale=0.65,
                               tip_length=0.22, tip_radius=0.08)
        self._plotter.add_mesh(arrow, color="#1687c7", name="preview-wind", reset_camera=False)
        self._preview_names.append("preview-wind")
        self._plotter.add_text(
            "VISTA PREVIA ILUSTRATIVA\\nFlecha = dirección del viento; no son resultados CFD.",
            name="preview-notice", position="lower_left", font_size=9, color="#284b63",
        )

    def set_camera_preset(self, preset: str) -> None:
        if not self._plotter:
            return
        views = {
            "isometric": ((1.55, -1.55, 1.05), (0.0, 0.0, 0.0), (0.0, 0.0, 1.0)),
            "side": ((0.0, -2.05, 0.0), (0.0, 0.0, 0.0), (0.0, 0.0, 1.0)),
            "front": ((2.05, 0.0, 0.0), (0.0, 0.0, 0.0), (0.0, 0.0, 1.0)),
            "top": ((0.0, 0.0, 2.05), (0.0, 0.0, 0.0), (0.0, 1.0, 0.0)),
            "rear": ((-2.05, 0.0, 0.0), (0.0, 0.0, 0.0), (0.0, 0.0, 1.0)),
        }
        if preset not in views:
            raise ValueError(f"Preset de cámara desconocido: {preset}")
        self._plotter.camera_position = views[preset]
        self._render_scene()

    def set_follow_rocket(self, enabled: bool) -> None:
        """Keep the focal point on the rocket for every animation tick."""
        self._following_rocket = bool(enabled)

    def set_cfd_layer(self, layer: str) -> None:
        if layer not in CFD_VISUAL_MODES:
            raise ValueError(f"Campo CFD desconocido: {layer}")
        if layer == self._cfd_layer and self._cfd_frame_index is not None:
            return
        self._cfd_layer = layer
        if self._cfd_frame_index is not None:
            self.set_cfd_frame(self._cfd_frame_index, force=True)

    def cfd_available_layers(self) -> dict[str, bool]:
        fields = set(self._cfd_available_fields)
        return {
            "velocity": "velocity" in fields,
            "pressure": "pressure" in fields,
            "vorticity": "vorticity" in fields,
            "turbulence": "turbulence" in fields,
            "drag": bool(self._cfd_frames),
            "lift": bool(self._cfd_frames),
            "side": bool(self._cfd_frames),
            "friction": bool(self._cfd_frames),
            "moment": bool(self._cfd_frames),
        }

    @staticmethod
    def _basis(direction: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
        helper = np.array((0.0, 0.0, 1.0))
        if abs(float(np.dot(direction, helper))) > 0.88:
            helper = np.array((1.0, 0.0, 0.0))
        first = np.cross(direction, helper)
        first /= max(float(np.linalg.norm(first)), 1e-9)
        second = np.cross(direction, first)
        second /= max(float(np.linalg.norm(second)), 1e-9)
        return first, second

    def _build_flow(self) -> None:
        if not self._plotter or not self._pv:
            return
        for name in self._flow_names:
            self._plotter.remove_actor(name, render=False)
        self._flow_names.clear()
        self._streamline_names.clear()
        self._vortex_names.clear()
        self._flow_paths.clear()
        self._vortex_meshes.clear()
        self._vortex_actors.clear()
        self._particle_mesh = None
        self._rain_mesh = None
        for title in ("Velocidad (m/s)", "Vorticidad (1/s)"):
            try:
                self._plotter.remove_scalar_bar(title, render=False)
            except (KeyError, ValueError):
                pass
        direction = flow_direction(self._alpha_deg, self._beta_deg)
        basis_u, basis_v = self._basis(direction)
        rng = np.random.default_rng(20260730)
        speed_scale = max(self._speed_mps, 0.2)
        seed_count = 76
        for index in range(seed_count):
            radius = math.sqrt((index + 0.7) / seed_count) * 1.04
            theta = index * 2.399963229728653
            radial = basis_u * (radius * math.cos(theta)) + basis_v * (radius * math.sin(theta))
            points: list[np.ndarray] = []
            scalar: list[float] = []
            phase = rng.uniform(0.0, 2.0 * math.pi)
            for step in range(42):
                t = step / 41.0
                axial = -1.85 + 3.70 * t
                base = direction * axial + radial
                near_body = math.exp(-((axial + 0.02) / 0.48) ** 2)
                radial_norm = max(float(np.linalg.norm(radial)), 0.08)
                avoidance = radial / radial_norm * near_body * (0.17 / (0.30 + radial_norm))
                wake = max(0.0, min(1.0, (axial - 0.05) / 1.25))
                swirl_strength = wake * (0.035 + 0.004 * sum(abs(value) for value in self._canards))
                swirl = (
                    basis_u * math.cos(phase + t * 16.0) +
                    basis_v * math.sin(phase + t * 16.0)
                ) * swirl_strength
                points.append(base + avoidance + swirl)
                local_speed = speed_scale * (0.72 + 0.43 * t + 0.20 * near_body)
                scalar.append(local_speed)
            path = np.asarray(points)
            self._flow_paths.append(path)
            line = self._pv.Spline(path, n_points=84)
            line.point_data["velocity_mps"] = np.linspace(min(scalar), max(scalar), line.n_points)
            name = f"streamline-{index}"
            self._plotter.add_mesh(
                line, scalars="velocity_mps", cmap="turbo", clim=(0.0, max(1.0, speed_scale * 1.4)),
                line_width=2.0, opacity=0.72, render_lines_as_tubes=True, name=name,
                show_scalar_bar=index == 0,
                scalar_bar_args={"title": "Velocidad (m/s)", "vertical": True, "position_x": 0.87, "position_y": 0.12, "height": 0.45},
                reset_camera=False,
            )
            self._flow_names.append(name)
            self._streamline_names.append(name)
        self._add_vortices(direction, basis_u, basis_v)
        particle_points = np.vstack([path[0] for path in self._flow_paths for _ in range(2)])
        particle_speed = np.full(len(particle_points), speed_scale)
        self._particle_mesh = self._pv.PolyData(particle_points)
        self._particle_mesh.point_data["velocity_mps"] = particle_speed
        name = "flow-particles"
        self._plotter.add_mesh(
            self._particle_mesh, scalars="velocity_mps", cmap="turbo",
            clim=(0.0, max(1.0, speed_scale * 1.4)), point_size=7,
            render_points_as_spheres=True, show_scalar_bar=False, name=name, reset_camera=False,
        )
        self._flow_names.append(name)
        if self._rain_rate_mm_h > 0.0:
            count = min(180, max(28, int(self._rain_rate_mm_h * 8)))
            rain_points = rng.uniform((-1.15, -1.15, -1.8), (1.15, 1.15, 1.8), (count, 3))
            self._rain_mesh = self._pv.PolyData(rain_points)
            self._rain_mesh.point_data["impact"] = np.linspace(0.0, 1.0, count)
            name = "rain-particles"
            self._plotter.add_mesh(
                self._rain_mesh, scalars="impact", cmap="winter", point_size=5,
                render_points_as_spheres=True, show_scalar_bar=False, opacity=0.8,
                name=name, reset_camera=False,
            )
            self._flow_names.append(name)
        self._apply_layer_visibility()

    def _add_vortices(self, direction: np.ndarray, basis_u: np.ndarray, basis_v: np.ndarray) -> None:
        if not self._plotter or not self._pv:
            return
        for index in range(8):
            points, values = self._vortex_points(index, direction, basis_u, basis_v, 100)
            vortex = self._pv.Spline(points, n_points=100)
            vortex.point_data["vorticity_s"] = values
            name = f"vortex-{index}"
            actor = self._plotter.add_mesh(
                vortex, scalars="vorticity_s", cmap="plasma", line_width=3.0, opacity=0.86,
                clim=(0.0, max(1.0, float(values.max()))),
                render_lines_as_tubes=True, show_scalar_bar=index == 0,
                scalar_bar_args={"title": "Vorticidad (1/s)", "vertical": True, "position_x": 0.03, "position_y": 0.12, "height": 0.35},
                name=name, reset_camera=False,
            )
            self._flow_names.append(name)
            self._vortex_names.append(name)
            self._vortex_meshes.append(vortex)
            self._vortex_actors.append(actor)

    def _vortex_points(
        self, index: int, direction: np.ndarray, basis_u: np.ndarray, basis_v: np.ndarray, count: int,
    ) -> tuple[np.ndarray, np.ndarray]:
        canard_strength = 0.06 + 0.006 * sum(abs(value) for value in self._canards)
        points: list[np.ndarray] = []
        values: list[float] = []
        phase = index * math.pi / 4.0
        for step in range(count):
            t = step / max(1, count - 1)
            axial = 0.08 + 1.55 * t
            radius = canard_strength * (0.8 + 0.75 * t)
            angle = phase + t * (5.5 * math.pi)
            points.append(direction * axial + basis_u * radius * math.cos(angle) + basis_v * radius * math.sin(angle))
            values.append(self._speed_mps * radius * (1.0 + t))
        return np.asarray(points), np.asarray(values)

    def _update_vortices(self) -> None:
        if not self._vortex_meshes:
            return
        direction = flow_direction(self._alpha_deg, self._beta_deg)
        basis_u, basis_v = self._basis(direction)
        for index, (mesh, actor) in enumerate(zip(self._vortex_meshes, self._vortex_actors)):
            points, values = self._vortex_points(index, direction, basis_u, basis_v, mesh.n_points)
            mesh.points = points
            mesh.point_data["vorticity_s"] = values
            actor.mapper.scalar_range = (0.0, max(1.0, float(values.max())))
            mesh.Modified()

    def _update_force_vectors(self) -> None:
        if not self._plotter or not self._pv:
            return
        for name in self._force_names:
            self._plotter.remove_actor(name, render=False)
        self._force_names.clear()
        self._force_actor_names.clear()
        direction = flow_direction(self._alpha_deg, self._beta_deg)
        basis_u, basis_v = self._basis(direction)
        metrics = aerodynamic_metrics(
            self._speed_mps, self._alpha_deg, self._beta_deg, self._canards, self._rain_rate_mm_h,
        )
        arrows = (
            ("drag", "Arrastre", "#ff3b30", direction, metrics["drag_n"]),
            ("lift", "Sustentación", "#47ff78", basis_u, metrics["lift_n"]),
            ("side", "Fuerza lateral", "#39a8ff", basis_v, metrics["side_n"]),
            ("friction", "Fricción", "#ff9f1c", direction, metrics["friction_n"]),
        )
        maximum = max((value for _, _, _, _, value in arrows), default=1.0)
        for index, (layer, _label, color, vector, value) in enumerate(arrows):
            scale = 0.18 + 0.62 * value / max(maximum, 1e-9)
            start = -direction * 0.12 + basis_u * (index - 1.5) * 0.035
            arrow = self._pv.Arrow(start=start, direction=vector, scale=scale, tip_length=0.24, tip_radius=0.10)
            name = f"force-{index}"
            self._plotter.add_mesh(arrow, color=color, name=name, reset_camera=False)
            self._force_names.append(name)
            self._force_actor_names[layer] = name
        self._force_metrics = metrics
        self._apply_layer_visibility()
        # Detailed OpenFOAM forces already have their own exact-component
        # legend. Never overwrite it with the retired preview estimate.
        if getattr(self, "_cfd_result", None) is None:
            self._refresh_force_legend()

    def _actor_visibility(self, name: str, visible: bool) -> None:
        if not self._plotter:
            return
        actor = getattr(self._plotter, "actors", {}).get(name)
        if actor is not None:
            actor.SetVisibility(bool(visible))

    def _scalar_bar_visibility(self, title: str, visible: bool) -> None:
        if not self._plotter:
            return
        scalar_bars = getattr(self._plotter, "scalar_bars", None)
        if scalar_bars is not None and title in scalar_bars:
            scalar_bars[title].SetVisibility(bool(visible))

    def _apply_layer_visibility(self) -> None:
        for name in self._streamline_names:
            self._actor_visibility(name, self.layer_visible("flow"))
        for name in self._vortex_names:
            self._actor_visibility(name, self.layer_visible("vortices"))
        self._actor_visibility("flow-particles", self.layer_visible("particles"))
        self._actor_visibility("rain-particles", self.layer_visible("rain"))
        self._actor_visibility("cfd-pressure-surface", self.layer_visible("cfd_field"))
        self._actor_visibility("cfd-wall-shear", self.layer_visible("friction"))
        self._actor_visibility("cfd-moment", self.layer_visible("vortices"))
        self._scalar_bar_visibility("Velocidad (m/s)", self.layer_visible("flow"))
        self._scalar_bar_visibility("Vorticidad (1/s)", self.layer_visible("vortices"))
        for layer, name in self._force_actor_names.items():
            self._actor_visibility(name, self.layer_visible(layer))
        if getattr(self, "_cfd_result", None) is None:
            self._refresh_force_legend()

    def _refresh_force_legend(self) -> None:
        if not self._plotter:
            return
        metrics = self._force_metrics
        lines = ["CARGAS DEL TÚNEL (estimadas)"]
        for layer, color, label, metric, precision in (
            ("drag", "Rojo", "arrastre", "drag_n", 3),
            ("lift", "Verde", "sustentación", "lift_n", 3),
            ("side", "Azul", "lateral", "side_n", 3),
            ("friction", "Naranja", "fricción", "friction_n", 4),
        ):
            if self.layer_visible(layer):
                lines.append(f"{color} {label} {metrics.get(metric, 0.0):.{precision}f} N")
        if self.layer_visible("vortices"):
            lines.append(f"Vorticidad {metrics.get('vorticity_s', 0.0):.2f} 1/s")
        if len(lines) == 1:
            lines.append("Sin cargas seleccionadas")
        self._plotter.add_text("\n".join(lines), name="force-legend", position="lower_right", font_size=8, color="#ffffff")

    def _update_caption(self) -> None:
        if not self._plotter:
            return
        east, north, up = self._wind_enu_mps
        self._plotter.add_text(
            f"FLUJO ANIMADO {self._speed_mps:.1f} m/s · α {self._alpha_deg:.1f}° · β {self._beta_deg:.1f}°\n"
            f"Clima {self._weather_source} · viento ENU ({east:.1f}, {north:.1f}, {up:.1f}) m/s · "
            f"{self._temperature_k - 273.15:.1f} °C · {self._pressure_pa:.0f} Pa · HR {self._humidity_ratio * 100:.0f}%\n"
            f"PID canards: C1 {self._canards[0]:+.1f}° · C2 {self._canards[1]:+.1f}° · "
            f"C3 {self._canards[2]:+.1f}° · C4 {self._canards[3]:+.1f}°\n"
            "PREVIA ILUSTRATIVA: sin fuerzas, vórtices ni líneas de corriente calculadas.\n"
            "Canards naranjas = ángulo aplicado · contorno blanco = referencia 0°. Ejes: +X nariz, +Y derecha, +Z arriba.",
            name="cfd-caption", position="upper_left", font_size=9, color="#284b63",
        )

    def _animate_flow(self) -> None:
        if not self._plotter or self._particle_mesh is None or not self._flow_paths:
            self._maintain_follow_camera()
            return
        self._particle_phase = (self._particle_phase + 0.006 + min(self._speed_mps, 100.0) * 0.00035) % 1.0
        points: list[np.ndarray] = []
        speeds: list[float] = []
        for index, path in enumerate(self._flow_paths):
            for offset in (0.0, 0.5):
                phase = (self._particle_phase + offset + index * 0.013) % 1.0
                position = phase * (len(path) - 1)
                low = int(position)
                high = min(low + 1, len(path) - 1)
                blend = position - low
                points.append(path[low] * (1.0 - blend) + path[high] * blend)
                speeds.append(self._speed_mps * (0.72 + 0.50 * phase))
        self._particle_mesh.points = np.asarray(points)
        self._particle_mesh.point_data["velocity_mps"] = np.asarray(speeds)
        self._particle_mesh.Modified()
        if self._rain_mesh is not None:
            rain = np.asarray(self._rain_mesh.points).copy()
            rain[:, 2] -= 0.025 + min(self._rain_rate_mm_h, 100.0) * 0.0005
            rain[rain[:, 2] < -1.8, 2] = 1.8
            self._rain_mesh.points = rain
            self._rain_mesh.Modified()
        self._render_scene()

    def _maintain_follow_camera(self) -> None:
        if not self._plotter or not self._following_rocket:
            return
        camera = self._plotter.camera
        position = np.asarray(camera.position, dtype=float)
        focal = np.asarray(camera.focal_point, dtype=float)
        camera.position = tuple(position - focal)
        camera.focal_point = (0.0, 0.0, 0.0)

    def export_surface(self, target: Path) -> Path | None:
        if not self._pv:
            return None
        source = application_root() / "data" / "models" / VISUAL_ROCKET_MODEL_STL
        if not source.is_file():
            return None
        mesh = self._pv.read(source)
        target.parent.mkdir(parents=True, exist_ok=True)
        mesh.save(target)
        return target

    @staticmethod
    def _scalar_bar(title: str, *, position_x: float = 0.84) -> dict[str, object]:
        """High-contrast scalar legend readable on the white CFD background."""
        return {
            "title": title, "vertical": True, "position_x": position_x,
            "position_y": 0.12, "height": 0.52, "width": 0.075,
            "n_labels": 7, "fmt": "%.3g", "color": "#17212b",
            "title_font_size": 12, "label_font_size": 10,
        }

    @staticmethod
    def _flow_reference(field: object) -> tuple[np.ndarray, float]:
        """Estimate the true freestream direction and speed from OpenFOAM U."""
        vectors = np.asarray(field.point_data["U"], dtype=float)
        finite = vectors[np.all(np.isfinite(vectors), axis=1)]
        if not len(finite):
            return np.array((-1.0, 0.0, 0.0)), 1.0
        direction = np.nanmedian(finite, axis=0)
        speed = float(np.linalg.norm(direction))
        if speed <= 1e-9:
            return np.array((-1.0, 0.0, 0.0)), 1.0
        return direction / speed, speed

    def _streamline_seed_cloud(self, field: object, *, compact: bool = False) -> object:
        """Place a circular rake immediately upstream of the physical rocket."""
        direction, _speed = self._flow_reference(field)
        basis_u, basis_v = self._basis(direction)
        centre = -direction * (0.5 * PHYSICAL_BODY_LENGTH_M + 0.17)
        rings = ((0.052, 10), (0.088, 14), (0.135, 18)) if compact else (
            (0.055, 10), (0.095, 14), (0.145, 18), (0.205, 22),
        )
        points: list[np.ndarray] = []
        for radius, count in rings:
            for angle in np.linspace(0.0, 2.0 * math.pi, count, endpoint=False):
                points.append(centre + basis_u * (radius * math.cos(angle)) + basis_v * (radius * math.sin(angle)))
        return self._pv.PolyData(np.asarray(points))

    def _scalar_feature_seed_cloud(self, field: object, scalar: str, *, count: int = 48) -> object:
        """Seed real high-gradient wake regions instead of the uniform inlet plane."""
        points = np.asarray(field.points, dtype=float)
        values = np.asarray(field.point_data[scalar], dtype=float)
        velocity = np.asarray(field.point_data["U"], dtype=float)
        speed = np.linalg.norm(velocity, axis=1)
        x0, x1, y0, y1, z0, z1 = self._FLOW_VIEW_BOUNDS
        radial = np.linalg.norm(points[:, 1:3], axis=1)
        finite = np.all(np.isfinite(points), axis=1) & np.isfinite(values) & np.isfinite(speed)
        near_body_and_wake = (
            (points[:, 0] >= max(x0, -0.90)) & (points[:, 0] <= min(x1, 0.58)) &
            (points[:, 1] >= y0) & (points[:, 1] <= y1) &
            (points[:, 2] >= z0) & (points[:, 2] <= z1) &
            (radial >= 0.035) & (radial <= 0.34) & (speed >= 0.25)
        )
        candidates = np.flatnonzero(finite & near_body_and_wake)
        if not len(candidates):
            return self._streamline_seed_cloud(field, compact=True)
        threshold = float(np.nanpercentile(values[candidates], 70.0))
        candidates = candidates[values[candidates] >= threshold]
        order = candidates[np.argsort(values[candidates])[::-1]][:6000]
        selected: list[int] = []
        minimum_spacing = 0.034
        for index in order:
            point = points[index]
            if not selected or np.min(np.linalg.norm(points[np.asarray(selected)] - point, axis=1)) >= minimum_spacing:
                selected.append(int(index))
                if len(selected) >= count:
                    break
        if len(selected) < min(12, count):
            selected = [int(index) for index in order[:count]]
        return self._pv.PolyData(points[np.asarray(selected, dtype=int)])

    def _wake_seed_cloud(self, field: object) -> object:
        """Place two compact circular rakes immediately behind the rocket."""
        direction, _speed = self._flow_reference(field)
        basis_u, basis_v = self._basis(direction)
        points: list[np.ndarray] = []
        for axial_distance in (0.50 * PHYSICAL_BODY_LENGTH_M + 0.03,
                               0.50 * PHYSICAL_BODY_LENGTH_M + 0.13):
            centre = direction * axial_distance
            for radius, count in ((0.050, 12), (0.095, 16), (0.155, 20)):
                for angle in np.linspace(0.0, 2.0 * math.pi, count, endpoint=False):
                    points.append(
                        centre + basis_u * (radius * math.cos(angle)) +
                        basis_v * (radius * math.sin(angle))
                    )
        return self._pv.PolyData(np.asarray(points))

    def _render_velocity_plane(self, field: object, clim: tuple[float, float]) -> None:
        """Add one contour plane behind the body, leaving the rocket unobstructed."""
        try:
            plane = field.slice(normal=(0.0, 1.0, 0.0), origin=(0.0, 0.16, 0.0))
            plane = plane.clip_box((-0.78, 0.88, 0.159, 0.161, -0.25, 0.25), invert=False)
            if not plane.n_points:
                return
            vectors = np.asarray(plane.point_data["U"], dtype=float)
            plane.point_data["velocity_mps"] = np.linalg.norm(vectors, axis=1)
            self._plotter.add_mesh(
                plane, scalars="velocity_mps", cmap="turbo", clim=clim, opacity=0.17,
                lighting=False, name="cfd-velocity-plane", show_scalar_bar=False,
                reset_camera=False,
            )
            self._streamline_names.append("cfd-velocity-plane")
        except (KeyError, TypeError, ValueError):
            return

    @staticmethod
    def _ranked_streamline_cells(lines: object, scalar: str, max_count: int) -> list[int]:
        """Prefer curved/high-gradient paths near the vehicle over uniform far-field lines."""
        connectivity = np.asarray(lines.lines, dtype=int)
        points = np.asarray(lines.points, dtype=float)
        values = np.asarray(lines.point_data[scalar], dtype=float)
        position = 0
        rows: list[tuple[int, float, float, float, float, float, float]] = []
        for cell_index in range(int(lines.n_cells)):
            count = int(connectivity[position])
            ids = connectivity[position + 1:position + 1 + count]
            position += count + 1
            if count < 3:
                continue
            path = points[ids]
            path_values = values[ids]
            radial_min = float(np.min(np.linalg.norm(path[:, 1:3], axis=1)))
            lateral_displacement = float(np.linalg.norm(path[-1, 1:3] - path[0, 1:3]))
            scalar_peak = float(np.nanpercentile(np.abs(path_values), 92.0))
            scalar_span = float(np.nanpercentile(path_values, 95.0) - np.nanpercentile(path_values, 5.0))
            segments = np.diff(path, axis=0)
            lengths = np.linalg.norm(segments, axis=1)
            valid = lengths > 1e-9
            unit = segments[valid] / lengths[valid, None]
            turning = (
                float(np.sum(np.arccos(np.clip(np.sum(unit[1:] * unit[:-1], axis=1), -1.0, 1.0))))
                if len(unit) > 1 else 0.0
            )
            path_length = float(np.sum(lengths))
            chord = float(np.linalg.norm(path[-1] - path[0]))
            loop_ratio = min(path_length / max(chord, 0.025), 8.0)
            rows.append((
                cell_index, radial_min, lateral_displacement, scalar_peak, abs(scalar_span), turning, loop_ratio,
            ))
        if not rows:
            return []
        peak_scale = max(row[3] for row in rows) or 1.0
        span_scale = max(row[4] for row in rows) or 1.0
        turning_scale = max(row[5] for row in rows) or 1.0
        if scalar == "vorticity_1ps":
            scored = [
                (
                    2.0 * row[3] / peak_scale + 1.2 * row[4] / span_scale +
                    2.8 * row[5] / turning_scale + 2.0 * min(row[6] / 2.5, 1.0) +
                    1.5 * max(0.0, 1.0 - row[1] / 0.20),
                    row[0],
                )
                for row in rows
            ]
            return [cell for _score, cell in sorted(scored, reverse=True)[:max_count]]
        peak_weight = 0.25 if scalar == "velocity_mps" else 2.0
        scored = [
            (
                peak_weight * row[3] / peak_scale + 2.3 * row[4] / span_scale +
                2.1 * min(row[2] / 0.18, 1.0) + 1.4 * max(0.0, 1.0 - row[1] / 0.18),
                row[0],
            )
            for row in rows
        ]
        return [cell for _score, cell in sorted(scored, reverse=True)[:max_count]]

    def _integrated_pathlines(
        self, field: object, scalar: str, *, max_count: int, compact: bool = False,
        feature_seeded: bool = False,
    ) -> object | None:
        """Integrate and retain only actual OpenFOAM paths that interact with the rocket."""
        vortex_vectors = next((name for name in ("vorticity", "curlU") if name in field.point_data), None)
        is_vortex_line = feature_seeded and scalar == "vorticity_1ps" and vortex_vectors is not None
        if is_vortex_line:
            seeds = self._scalar_feature_seed_cloud(field, scalar)
            vector_name = str(vortex_vectors)
            integration_direction = "both"
            max_length = 0.85
        elif feature_seeded:
            seeds = self._wake_seed_cloud(field)
            vector_name = "U"
            integration_direction = "forward"
            max_length = 1.30
        else:
            seeds = self._streamline_seed_cloud(field, compact=compact)
            vector_name = "U"
            integration_direction = "forward"
            max_length = 2.0
        lines = field.streamlines_from_source(
            seeds, vectors=vector_name, integration_direction=integration_direction,
            max_length=max_length,
            initial_step_length=0.004, max_steps=2400, compute_vorticity=False,
        )
        if not lines.n_points or scalar not in lines.point_data:
            return None
        selected = self._ranked_streamline_cells(lines, scalar, max_count)
        if not selected:
            return None
        view_bounds = (-0.78, 0.72, -0.30, 0.30, -0.30, 0.30) if is_vortex_line else self._FLOW_VIEW_BOUNDS
        retained = lines.extract_cells(selected).extract_surface(algorithm="dataset_surface").clip_box(
            view_bounds, invert=False
        ).extract_surface(algorithm="dataset_surface")
        retained.field_data["trajectory_count"] = np.asarray([len(selected)], dtype=np.int32)
        return retained

    @staticmethod
    def _trajectory_count(lines: object) -> int:
        values = lines.field_data.get("trajectory_count")
        return int(np.asarray(values).ravel()[0]) if values is not None and len(values) else int(lines.n_cells)

    def _add_pathline_arrows(
        self, lines: object, *, scalar: str, clim: tuple[float, float], cmap: str,
        actor_name: str, log_scale: bool = False, max_glyphs: int | None = None,
        arrow_scale: float | None = None,
    ) -> None:
        """Add sparse directional glyphs without hiding the integrated trajectories."""
        vector_name = next(
            (name for name in ("vorticity", "curlU") if scalar == "vorticity_1ps" and name in lines.point_data),
            "U",
        )
        if vector_name not in lines.point_data or scalar not in lines.point_data or lines.n_points < 2:
            return
        points = np.asarray(lines.points, dtype=float)
        vectors = np.asarray(lines.point_data[vector_name], dtype=float)
        values = np.asarray(lines.point_data[scalar], dtype=float)
        finite = np.all(np.isfinite(points), axis=1) & np.all(np.isfinite(vectors), axis=1) & np.isfinite(values)
        candidates = np.flatnonzero(finite)
        if not len(candidates):
            return
        glyph_limit = max_glyphs if max_glyphs is not None else (72 if scalar == "vorticity_1ps" else 150)
        chosen = candidates[np.linspace(0, len(candidates) - 1, min(glyph_limit, len(candidates)), dtype=int)]
        direction = vectors[chosen]
        magnitude = np.linalg.norm(direction, axis=1)
        valid = magnitude > 1e-9
        if not np.any(valid):
            return
        cloud = self._pv.PolyData(points[chosen][valid])
        cloud["flow_direction"] = direction[valid] / magnitude[valid, None]
        cloud[scalar] = values[chosen][valid]
        arrow = self._pv.Arrow(tip_length=0.50, tip_radius=0.18, shaft_radius=0.060)
        glyphs = cloud.glyph(
            orient="flow_direction", scale=False,
            factor=arrow_scale if arrow_scale is not None else (0.045 if scalar == "vorticity_1ps" else 0.032),
            geom=arrow,
        )
        self._plotter.add_mesh(
            glyphs, scalars=scalar, cmap=cmap, clim=clim, log_scale=log_scale,
            opacity=0.90, name=actor_name, show_scalar_bar=False, reset_camera=False,
        )

    def _add_vortex_rotation_rings(self, field: object) -> None:
        """Render compact local rotation indicators from exported vorticity vectors.

        A ring is a vorticity glyph: its plane is normal to the local curl(U),
        its arrow follows the measured rotation direction, and its colour comes
        from the local vorticity magnitude.  It is deliberately not presented
        as a streamline.
        """
        vector_name = next((name for name in ("vorticity", "curlU") if name in field.point_data), None)
        if vector_name is None:
            return
        points = np.asarray(field.points, dtype=float)
        vectors = np.asarray(field.point_data[vector_name], dtype=float)
        magnitude = np.linalg.norm(vectors, axis=1)
        radial = np.linalg.norm(points[:, 1:3], axis=1)
        finite = np.all(np.isfinite(points), axis=1) & np.all(np.isfinite(vectors), axis=1)
        nearby = (
            (points[:, 0] >= -0.62) & (points[:, 0] <= 0.55) &
            (radial >= 0.035) & (radial <= 0.29) & (magnitude > 1e-9)
        )
        candidates = np.flatnonzero(finite & nearby)
        if not len(candidates):
            return
        cutoff = float(np.nanpercentile(magnitude[candidates], 86.0))
        ordered = candidates[magnitude[candidates] >= cutoff]
        ordered = ordered[np.argsort(magnitude[ordered])[::-1]][:4000]
        selected: list[int] = []
        for index in ordered:
            if not selected or np.min(np.linalg.norm(points[np.asarray(selected)] - points[index], axis=1)) >= 0.115:
                selected.append(int(index))
                if len(selected) == 6:
                    break
        if not selected:
            return
        chosen = np.asarray(selected, dtype=int)
        values = magnitude[chosen]
        positive = magnitude[np.isfinite(magnitude) & (magnitude > 0.0)]
        clim = (
            max(float(np.nanpercentile(positive, 5.0)), 1e-12),
            max(float(np.nanpercentile(positive, 97.0)), 1e-11),
        )
        normalised = (values - float(np.min(values))) / max(float(np.ptp(values)), 1e-12)
        ring_points: list[np.ndarray] = []
        ring_lines: list[np.ndarray] = []
        ring_values: list[np.ndarray] = []
        arrow_points: list[np.ndarray] = []
        arrow_vectors: list[np.ndarray] = []
        arrow_values: list[float] = []
        offset = 0
        angles = np.linspace(0.0, 2.0 * math.pi, 49)
        for index, value, relative in zip(chosen, values, normalised):
            axis = vectors[index] / max(float(magnitude[index]), 1e-12)
            first, second = self._basis(axis)
            centre = points[index].copy()
            radial_direction = np.array((0.0, centre[1], centre[2]))
            radial_length = float(np.linalg.norm(radial_direction))
            if radial_length > 1e-9:
                centre += 0.020 * radial_direction / radial_length
            radius = 0.045 + 0.030 * float(relative)
            circle = np.asarray([
                centre + radius * (math.cos(angle) * first + math.sin(angle) * second)
                for angle in angles
            ])
            ring_points.append(circle)
            ring_lines.append(np.concatenate(([len(circle)], np.arange(offset, offset + len(circle), dtype=int))))
            ring_values.append(np.full(len(circle), value, dtype=float))
            arrow_angle = 5.25
            arrow_points.append(centre + radius * (math.cos(arrow_angle) * first + math.sin(arrow_angle) * second))
            arrow_vectors.append(-math.sin(arrow_angle) * first + math.cos(arrow_angle) * second)
            arrow_values.append(float(value))
            offset += len(circle)
        rings = self._pv.PolyData(np.vstack(ring_points))
        rings.lines = np.concatenate(ring_lines)
        rings["vorticity_1ps"] = np.concatenate(ring_values)
        tubes = rings.tube(radius=0.0032, n_sides=10)
        self._plotter.add_mesh(
            tubes, scalars="vorticity_1ps", cmap="viridis", clim=clim, log_scale=True,
            opacity=0.94, smooth_shading=True, ambient=0.24, specular=0.50, specular_power=24,
            name="cfd-vortex-rings", show_scalar_bar=True,
            scalar_bar_args=self._scalar_bar("Vorticidad (1/s)"), reset_camera=False,
        )
        self._vortex_names.append("cfd-vortex-rings")
        arrows = self._pv.PolyData(np.asarray(arrow_points))
        arrows["rotation_direction"] = np.asarray(arrow_vectors)
        arrows["vorticity_1ps"] = np.asarray(arrow_values)
        glyphs = arrows.glyph(
            orient="rotation_direction", scale=False, factor=0.036,
            geom=self._pv.Arrow(tip_length=0.50, tip_radius=0.20, shaft_radius=0.065),
        )
        self._plotter.add_mesh(
            glyphs, scalars="vorticity_1ps", cmap="viridis", clim=clim, log_scale=True,
            opacity=0.98, name="cfd-vortex-ring-arrows", show_scalar_bar=False, reset_camera=False,
        )
        self._vortex_names.append("cfd-vortex-ring-arrows")
        self._plotter.add_text(
            f"ANILLOS DE VORTICIDAD · OPENFOAM\n{len(chosen)} zonas de rotación local · "
            f"{clim[0]:.3g}–{clim[1]:.3g} 1/s\nAnillo y flecha = sentido local de curl(U)",
            name="cfd-mode-info", position="upper_left", font_size=9, color="#17212b",
        )

    def _render_surface_fields(self, frame: object) -> None:
        """Render only the selected wall quantity from the exported surface."""
        surface_path = _frame_value(frame, "surface_vtk_path")
        if not self._plotter or not surface_path or not Path(surface_path).is_file():
            return
        try:
            surface = self._pv.read(surface_path)
            arrays = set(surface.array_names)
            pressure = next((name for name in ("p", "p_rgh", "pressure_pa") if name in arrays), None)
            if pressure and self._cfd_layer == "pressure":
                density = 1.0 if pressure == "pressure_pa" else float(getattr(self._cfd_result, "air_density_kg_m3", 1.225))
                values = np.asarray(surface[pressure], dtype=float) * density
                surface["pressure_pa"] = values
                clim = robust_scalar_range(values, symmetric=True)
                self._plotter.add_mesh(
                    surface, scalars="pressure_pa", cmap="coolwarm", clim=clim, opacity=1.0,
                    n_colors=14, smooth_shading=False, show_edges=False,
                    name="cfd-pressure-surface", show_scalar_bar=True,
                    scalar_bar_args=self._scalar_bar("Presión manométrica (Pa)"), reset_camera=False,
                )
                self._plotter.add_text(
                    f"PRESIÓN SOBRE LA SUPERFICIE\nRango robusto: {clim[0]:.3g} a {clim[1]:.3g} Pa\n"
                    "Rojo = sobrepresión · azul = succión",
                    name="cfd-mode-info", position="upper_left", font_size=9, color="#17212b",
                )
            shear = next((name for name in ("wallShearStress", "wallShear", "tauWall") if name in arrays), None)
            if shear and self._cfd_layer == "friction":
                source = surface if shear in surface.point_data else surface.cell_data_to_point_data(pass_cell_data=False)
                vector = np.asarray(source.point_data[shear], dtype=float)
                points = np.asarray(source.points)
                magnitude = np.linalg.norm(vector, axis=1)
                clim = robust_scalar_range(magnitude, lower=1.0, upper=99.0)
                source.point_data["wall_shear_pa"] = magnitude
                self._plotter.add_mesh(
                    source, scalars="wall_shear_pa", cmap="inferno", clim=clim, opacity=0.94,
                    n_colors=24, smooth_shading=True, show_edges=False,
                    name="cfd-wall-shear-surface", show_scalar_bar=True,
                    scalar_bar_args=self._scalar_bar("Esfuerzo cortante (Pa)"), reset_camera=False,
                )
                threshold = float(np.nanpercentile(magnitude, 45.0))
                candidates = np.flatnonzero(magnitude >= threshold)
                selected = candidates[np.linspace(0, len(candidates) - 1, min(240, len(candidates)), dtype=int)]
                normals_source = source.compute_normals(point_normals=True, cell_normals=False, inplace=False)
                normals = np.asarray(normals_source.point_data.get("Normals", np.zeros_like(points)), dtype=float)
                cloud = self._pv.PolyData(points[selected] + 0.0015 * normals[selected])
                selected_vector = vector[selected]
                selected_magnitude = np.linalg.norm(selected_vector, axis=1)
                cloud["wall_shear_direction"] = selected_vector / np.maximum(selected_magnitude[:, None], 1e-12)
                cloud["wall_shear_pa"] = selected_magnitude
                arrow = self._pv.Arrow(tip_length=0.50, tip_radius=0.18, shaft_radius=0.060)
                glyphs = cloud.glyph(orient="wall_shear_direction", scale=False, factor=0.034, geom=arrow)
                self._plotter.add_mesh(
                    glyphs, scalars="wall_shear_pa", cmap="inferno", clim=clim, opacity=0.88,
                    name="cfd-wall-shear", show_scalar_bar=False,
                    reset_camera=False,
                )
                contours = source.contour(isosurfaces=8, scalars="wall_shear_pa")
                if contours.n_points:
                    self._plotter.add_mesh(
                        contours, color="#27384a", opacity=0.46, line_width=1.0,
                        name="cfd-wall-shear-contours", show_scalar_bar=False, reset_camera=False,
                    )
                self._force_actor_names["friction"] = "cfd-wall-shear"
        except (OSError, KeyError, ValueError, TypeError):
            return

    def _build_real_streamlines(self, field: object) -> None:
        """Use VTK's vector integrator; never substitute decorative paths."""
        for name in self._streamline_names:
            self._plotter.remove_actor(name, render=False)
        self._streamline_names.clear()
        if "velocity" not in self._cfd_available_fields:
            return
        try:
            lines = self._integrated_pathlines(field, "velocity_mps", max_count=34, compact=True)
            if lines is not None and lines.n_points:
                lines["stream_velocity_mps"] = np.linalg.norm(np.asarray(lines["U"]), axis=1)
                clim = robust_scalar_range(lines["stream_velocity_mps"], lower=1.0, upper=99.0)
                tubes = lines.tube(radius=0.0025, n_sides=7)
                self._plotter.add_mesh(
                    tubes, scalars="stream_velocity_mps", cmap="turbo", clim=clim, opacity=0.86,
                    smooth_shading=True, name="cfd-streamlines", show_scalar_bar=True,
                    scalar_bar_args=self._scalar_bar("Velocidad (m/s)"),
                    reset_camera=False,
                )
                self._streamline_names.append("cfd-streamlines")
                self._add_pathline_arrows(
                    lines, scalar="stream_velocity_mps", clim=clim, cmap="turbo",
                    actor_name="cfd-streamline-arrows",
                )
                self._streamline_names.append("cfd-streamline-arrows")
                self._render_velocity_plane(field, clim)
                self._plotter.add_text(
                    f"LÍNEAS DE CORRIENTE OPENFOAM\n{self._trajectory_count(lines)} trayectorias · "
                    f"{clim[0]:.3g}–{clim[1]:.3g} m/s\nSembradas aguas arriba del cohete",
                    name="cfd-mode-info", position="upper_left", font_size=9, color="#17212b",
                )
        except Exception:
            return

    def _render_scalar_pathlines(
        self, field: object, *, scalar: str, title: str, unit: str, cmap: str, actor_name: str,
        log_scale: bool = False,
    ) -> None:
        """Render a selected CFD magnitude only as real, ranked flow trajectories."""
        try:
            is_vortex = scalar == "vorticity_1ps"
            max_count = 12 if is_vortex else 72
            lines = self._integrated_pathlines(
                field, scalar, max_count=max_count, compact=True, feature_seeded=True,
            )
            if lines is None or not lines.n_points:
                return
            values = np.asarray(lines.point_data[scalar], dtype=float)
            clim = robust_scalar_range(values, lower=5.0, upper=95.0)
            if log_scale:
                positive = values[np.isfinite(values) & (values > 0.0)]
                if not len(positive):
                    return
                clim = (
                    max(float(np.nanpercentile(positive, 5.0)), 1e-12),
                    max(float(np.nanpercentile(positive, 97.0)), 1e-11),
                )
            tubes = lines.tube(radius=0.0036 if is_vortex else 0.0024, n_sides=9)
            self._plotter.add_mesh(
                tubes, scalars=scalar, cmap=cmap, clim=clim, log_scale=log_scale,
                opacity=0.90 if is_vortex else 0.96, smooth_shading=True,
                ambient=0.22 if is_vortex else 0.0, specular=0.48 if is_vortex else 0.0,
                specular_power=24 if is_vortex else 1.0, name=actor_name, show_scalar_bar=True,
                scalar_bar_args=self._scalar_bar(f"{title} ({unit})"), reset_camera=False,
            )
            self._vortex_names.append(actor_name)
            arrow_name = f"{actor_name}-arrows"
            self._add_pathline_arrows(
                lines, scalar=scalar, clim=clim, cmap=cmap,
                actor_name=arrow_name, log_scale=log_scale,
                max_glyphs=16 if is_vortex else None, arrow_scale=0.031 if is_vortex else None,
            )
            self._vortex_names.append(arrow_name)
            self._plotter.add_text(
                f"{'NÚCLEOS VORTICALES' if is_vortex else title.upper()} · OPENFOAM\n"
                f"{self._trajectory_count(lines)} trayectorias seleccionadas · {clim[0]:.3g}–{clim[1]:.3g} {unit}\n"
                "Sin envolventes ni volúmenes decorativos",
                name="cfd-mode-info", position="upper_left", font_size=9, color="#17212b",
            )
        except Exception:
            return

    def _add_real_vorticity_surface(self, field: object) -> None:
        """Show local OpenFOAM vorticity as directional rotation rings."""
        if "vorticity" in self._cfd_available_fields:
            self._add_vortex_rotation_rings(field)

    def _add_turbulence_pathlines(self, field: object) -> None:
        if "turbulence" in self._cfd_available_fields:
            self._render_scalar_pathlines(
                field, scalar="turbulence_intensity_pct", title="Intensidad turbulenta", unit="%",
                cmap="turbo", actor_name="cfd-turbulence-lines",
            )

    def _add_openfoam_force_vectors(self, result: object) -> None:
        for name in self._force_names:
            self._plotter.remove_actor(name, render=False)
        self._force_names.clear()
        self._force_actor_names.clear()
        rocket_force = np.asarray(result.force_n, dtype=float)
        recovery_force = np.asarray(getattr(result, "recovery_force_n", (0.0, 0.0, 0.0)), dtype=float)
        projected = aerodynamic_force_vectors(
            rocket_force + recovery_force,
            getattr(result, "inlet_velocity_body_mps", (1.0, 0.0, 0.0)),
        )
        components = [
            ("drag", "Arrastre", "#d62828", projected["drag"]),
            ("lift", "Sustentación", "#218c4a", projected["lift"]),
            ("side", "Fuerza lateral", "#1769aa", projected["side"]),
        ]
        viscous = getattr(result, "viscous_force_n", None)
        if viscous is not None:
            vector = np.asarray(viscous, dtype=float)
            if float(np.linalg.norm(vector)) > 1e-12:
                components.append(("friction", "Fricción viscosa", "#f59e0b", vector))
        maximum = max((float(np.linalg.norm(vector)) for *_rest, vector in components), default=0.0)
        legend = [
            "CARGAS AERODINÁMICAS DEL SISTEMA (N)"
            if float(np.linalg.norm(recovery_force)) > 1e-12
            else "FUERZAS SOBRE EL COHETE · CFD/OpenFOAM (N)"
        ]
        for index, (layer, label, color, vector) in enumerate(components):
            magnitude = float(np.linalg.norm(vector))
            if magnitude <= 1e-12:
                continue
            origin = np.asarray(getattr(result, "center_of_gravity_body_m", (0.0, 0.0, 0.0)), dtype=float)
            arrow = self._pv.Arrow(start=origin, direction=vector / magnitude,
                                   scale=0.10 + 0.42 * magnitude / maximum,
                                   tip_length=0.22, tip_radius=0.065)
            name = f"openfoam-force-{index}"
            self._plotter.add_mesh(arrow, color=color, name=name, reset_camera=False)
            self._force_names.append(name)
            self._force_actor_names[layer] = name
            legend.append(f"{label}: {magnitude:.3g} N")
        self._plotter.add_text("\n".join(legend), name="force-legend", position="upper_right", font_size=8, color="#202b33")
        self._apply_layer_visibility()

    def _add_openfoam_moment(self, frame: object) -> None:
        """Show the integrated moment with an oriented arc, axis and arrowhead."""
        if not self._plotter or not self._pv:
            return
        self._plotter.remove_actor("cfd-moment", render=False)
        moment = np.asarray(_frame_value(frame, "moment_nm", (0.0, 0.0, 0.0)), dtype=float)
        magnitude = float(np.linalg.norm(moment))
        if magnitude <= 1e-12:
            return
        try:
            axis = moment / magnitude
            origin = np.asarray(_frame_value(frame, "center_of_gravity_body_m", (0.0, 0.0, 0.0)), dtype=float)
            arc = self._pv.CircularArcFromNormal(
                normal=axis, polar=np.array((0.0, 0.28, 0.0)), angle=275.0,
                center=origin, resolution=72,
            )
            tube = arc.tube(radius=0.009, n_sides=10)
            tangent = np.asarray(arc.points[-1], dtype=float) - np.asarray(arc.points[-3], dtype=float)
            tangent /= max(float(np.linalg.norm(tangent)), 1e-12)
            tip = self._pv.Arrow(
                start=np.asarray(arc.points[-1], dtype=float) - tangent * 0.045,
                direction=tangent, scale=0.13, tip_length=0.48, tip_radius=0.12, shaft_radius=0.025,
            )
            axis_arrow = self._pv.Arrow(
                start=origin, direction=axis, scale=0.24,
                tip_length=0.30, tip_radius=0.09, shaft_radius=0.020,
            )
            self._plotter.add_mesh(tube, color="#c850ff", name="cfd-moment", reset_camera=False)
            self._plotter.add_mesh(tip, color="#f08cff", name="cfd-moment-tip", reset_camera=False)
            self._plotter.add_mesh(axis_arrow, color="#8e35c9", name="cfd-moment-axis", reset_camera=False)
            self._force_names.extend(("cfd-moment", "cfd-moment-tip", "cfd-moment-axis"))
            self._force_actor_names["vortices"] = "cfd-moment"
        except (TypeError, ValueError):
            return

    def _add_selected_force_vector(self, frame: object, layer: str) -> None:
        """Draw one integrated OpenFOAM load from the vehicle centre of gravity."""
        force = np.asarray(_frame_value(frame, "force_n", (0.0, 0.0, 0.0)), dtype=float)
        recovery = np.asarray(_frame_value(frame, "recovery_force_n", (0.0, 0.0, 0.0)), dtype=float)
        system_force = force + recovery
        projected = aerodynamic_force_vectors(
            system_force, _frame_value(frame, "inlet_velocity_body_mps", (1.0, 0.0, 0.0)),
        )
        viscous = _frame_value(frame, "viscous_force_n")
        definitions = {
            "drag": ("Arrastre", "#ff334c", projected["drag"]),
            "lift": ("Sustentación", "#38e56f", projected["lift"]),
            "side": ("Fuerza lateral", "#35a7ff", projected["side"]),
            "friction": ("Fricción viscosa", "#ff9f1c", np.asarray(viscous if viscous is not None else force, dtype=float)),
        }
        if layer not in definitions:
            return
        label, color, vector = definitions[layer]
        magnitude = float(np.linalg.norm(vector))
        if magnitude > 1e-12:
            direction = vector / magnitude
            total = max(float(np.linalg.norm(system_force)), magnitude, 1e-12)
            # A longitudinal load must extend beyond the 0.451 m half-body;
            # otherwise the opaque rocket hides the complete arrow.
            visual_length = 0.60 + 0.20 * min(magnitude / total, 1.0)
            arrow = self._pv.Arrow(
                start=np.asarray(_frame_value(frame, "center_of_gravity_body_m", (0.0, 0.0, 0.0)), dtype=float),
                direction=direction, scale=visual_length,
                tip_length=0.24, tip_radius=0.075, shaft_radius=0.022,
            )
            name = f"openfoam-selected-{layer}"
            self._plotter.add_mesh(arrow, color=color, name=name, reset_camera=False)
            self._force_names.append(name)
            self._force_actor_names[layer] = name
        source_note = (
            "Sistema = cohete OpenFOAM + recuperación q·CdS 6-DoF"
            if float(np.linalg.norm(recovery)) > 1e-12 and layer != "friction"
            else "Superficie del cohete integrada por OpenFOAM"
        )
        self._plotter.add_text(
            f"{label.upper()} · RESULTADO INTEGRADO\n|F| = {magnitude:.5g} N\n"
            f"Vector = ({vector[0]:+.4g}, {vector[1]:+.4g}, {vector[2]:+.4g}) N\n"
            f"{source_note}\nOrigen de la flecha: centro de gravedad",
            name="cfd-mode-info", position="upper_left", font_size=9, color="#17212b",
        )

    def _clear_active_cfd_visual(self) -> None:
        """Release the previous field representation before creating another."""
        if not self._plotter:
            return
        names = {
            *self._streamline_names, *self._vortex_names, *self._force_names,
            *self._force_actor_names.values(), "cfd-velocity-glyphs", "cfd-streamlines",
            "cfd-velocity-plane", "cfd-vorticity-surface", "cfd-pressure-surface",
            "cfd-vorticity-lines", "cfd-vortex-rings", "cfd-vortex-ring-arrows", "cfd-turbulence-lines", "cfd-wall-shear",
            "cfd-wall-shear-surface", "cfd-wall-shear-contours", "cfd-moment", "cfd-moment-tip",
            "cfd-moment-axis", "force-legend", "cfd-mode-info", "preview-notice", "cfd-caption",
            "openfoam-selected-drag",
            "openfoam-selected-lift", "openfoam-selected-side", "openfoam-selected-friction",
        }
        for name in names:
            self._plotter.remove_actor(name, render=False)
        for title in (
            "Velocidad (m/s)", "Presión manométrica (Pa)", "Vorticidad (1/s)",
            "Intensidad turbulenta (%)", "Esfuerzo cortante (Pa)",
        ):
            try:
                self._plotter.remove_scalar_bar(title, render=False)
            except (KeyError, ValueError):
                pass
        self._streamline_names.clear(); self._vortex_names.clear(); self._force_names.clear()
        self._force_actor_names.clear(); self._cfd_dataset = None
        gc.collect()

    def _set_visual_mode_background(self) -> None:
        """Use a soft neutral gradient without sacrificing CFD contrast."""
        self._plotter.set_background("#f3f5f7", top="#cfd5db")

    def _discover_cfd_fields(self, field: object) -> None:
        arrays = set(field.point_data)
        if "U" in arrays:
            vector = np.asarray(field.point_data["U"])
            if vector.ndim == 2 and vector.shape[1] == 3:
                field.point_data["velocity_mps"] = np.linalg.norm(vector, axis=1)
                self._cfd_available_fields["velocity"] = "velocity_mps"
        pressure = next((name for name in ("p", "p_rgh") if name in arrays), None)
        if pressure:
            field.point_data["pressure_pa"] = np.asarray(field.point_data[pressure]) * float(
                getattr(self._cfd_result, "air_density_kg_m3", 1.225)
            )
            self._cfd_available_fields["pressure"] = "pressure_pa"
        vortex = next((name for name in ("vorticity", "curlU") if name in arrays), None)
        if vortex:
            values = np.asarray(field.point_data[vortex])
            field.point_data["vorticity_1ps"] = np.linalg.norm(values, axis=1) if values.ndim == 2 else values
            self._cfd_available_fields["vorticity"] = "vorticity_1ps"
        if "Q" in arrays:
            self._cfd_available_fields["q_criterion"] = "Q"
        if "k" in arrays and "U" in arrays:
            k_values = np.maximum(np.asarray(field.point_data["k"], dtype=float), 0.0)
            speed = np.linalg.norm(np.asarray(field.point_data["U"], dtype=float), axis=1)
            field.point_data["turbulence_intensity_pct"] = (
                100.0 * np.sqrt((2.0 / 3.0) * k_values) / np.maximum(speed, 0.25)
            )
            self._cfd_available_fields["turbulence"] = "turbulence_intensity_pct"

    def _render_active_cfd_mode(self, field: object | None, frame: object) -> None:
        mode = self._cfd_layer
        if mode == "velocity" and field is not None:
            self._build_real_streamlines(field)
        elif mode == "pressure":
            self._render_surface_fields(frame)
        elif mode == "vorticity" and field is not None:
            self._add_real_vorticity_surface(field)
        elif mode == "turbulence" and field is not None:
            self._add_turbulence_pathlines(field)
        elif mode in {"drag", "lift", "side"}:
            self._add_selected_force_vector(frame, mode)
        elif mode == "friction":
            self._render_surface_fields(frame)
            self._add_selected_force_vector(frame, mode)
        elif mode == "moment":
            self._add_openfoam_moment(frame)
            moment = np.asarray(_frame_value(frame, "moment_nm", (0.0, 0.0, 0.0)), dtype=float)
            magnitude = float(np.linalg.norm(moment))
            self._plotter.add_text(
                f"MOMENTO AERODINÁMICO INTEGRADO\n|M| = {magnitude:.5g} N·m\n"
                f"Vector = ({moment[0]:+.4g}, {moment[1]:+.4g}, {moment[2]:+.4g}) N·m\n"
                "Arco = sentido · eje = orientación",
                name="cfd-mode-info", position="upper_left", font_size=9, color="#17212b",
            )

    def set_cfd_frame(self, index: int, *, force: bool = False) -> tuple[float, float, float, float] | None:
        """Select one discrete OpenFOAM state; no field interpolation is used."""
        if not self._plotter or not self._pv or not self._cfd_frames:
            return None
        index = min(max(0, int(index)), len(self._cfd_frames) - 1)
        if not force and index == self._cfd_frame_index:
            frame = self._cfd_frames[index]
            return tuple(float(value) for value in _frame_value(frame, "canard_deg", self._canards))
        frame = self._cfd_frames[index]
        vtk_path = _frame_value(frame, "vtk_path")
        if not vtk_path or not Path(vtk_path).is_file():
            return None
        self._clear_active_cfd_visual()
        self._set_visual_mode_background()
        self._cfd_frame_index = index
        field = None
        try:
            # Forces, moment and surface pressure do not need the 40–50 MB
            # internal volume.  Read it only for velocity or vorticity.
            if self._cfd_layer in {"velocity", "vorticity", "turbulence"}:
                field = self._pv.read(vtk_path)
                point_arrays = set(field.point_data)
                required = {
                    "velocity": "U", "vorticity": "vorticity", "turbulence": "k",
                }[self._cfd_layer]
                if required not in point_arrays and required in set(field.cell_data):
                    field = field.cell_data_to_point_data(pass_cell_data=False)
                self._discover_cfd_fields(field)
            self._render_active_cfd_mode(field, frame)
            self.set_canard_deflections(tuple(float(value) for value in _frame_value(frame, "canard_deg", self._canards)))
            self._cfd_dataset = None
            field = None
            gc.collect()
            self._render_scene()
        except Exception as exc:
            self._cfd_dataset = None
            field = None
            gc.collect()
            self._plotter.add_text(f"No se pudo mostrar el estado VTK: {exc}", name="cfd-result", position="lower_left", font_size=9, color="#8b3a1d")
            return None
        return tuple(float(value) for value in _frame_value(frame, "canard_deg", self._canards))

    def show_cfd_result(self, result: object) -> None:
        """Render only fields exported by a completed OpenFOAM case."""
        if not self._plotter or not self._pv:
            return
        self._clear_result_actors()
        # Preview labels and its wind arrow are intentionally illustrative;
        # remove them before presenting the OpenFOAM post-processing scene.
        for name in (*self._preview_names, "preview-notice", "cfd-caption"):
            self._plotter.remove_actor(name, render=False)
        self._preview_names.clear()
        if getattr(result, "backend", "") != "OpenFOAM" or not bool(getattr(result, "converged", False)):
            self._plotter.add_text(
                "RESULTADO NO VALIDADO — no se habilitan campos hasta demostrar convergencia y calidad de malla.",
                name="cfd-result", position="lower_left", font_size=9, color="#8b3a1d",
            )
            self._render_scene()
            return
        vtk_path = getattr(result, "vtk_path", None)
        if not vtk_path or not Path(vtk_path).is_file():
            self._plotter.add_text(
                "CFD/OpenFOAM terminado, pero foamToVTK no exportó un campo legible.",
                name="cfd-result", position="lower_left", font_size=9, color="#8b3a1d",
            )
            self._render_scene()
            return
        try:
            self._cfd_result = result
            # Start every newly loaded snapshot in the bounded streamline
            # view. This also discovers which volume arrays are available.
            self._cfd_layer = "velocity"
            frames = tuple(_normalise_cfd_frame(frame) for frame in getattr(result, "frames", ()))
            if not frames:
                # Backward-compatible stationary result: still an actual VTK,
                # represented as precisely one discrete CFD frame.
                frames = (SimpleNamespace(
                    time_s=0.0, canard_deg=self._canards, vtk_path=vtk_path, surface_vtk_path=None,
                    force_n=result.force_n, moment_nm=result.moment_nm,
                    pressure_force_n=getattr(result, "pressure_force_n", None),
                    viscous_force_n=getattr(result, "viscous_force_n", None),
                    inlet_velocity_body_mps=getattr(result, "inlet_velocity_body_mps", (1.0, 0.0, 0.0)),
                    recovery_force_n=getattr(result, "recovery_force_n", (0.0, 0.0, 0.0)),
                    center_of_gravity_body_m=getattr(result, "center_of_gravity_body_m", (0.0, 0.0, 0.0)),
                ),)
            self._cfd_frames = frames
            self._plotter.add_text(
                "CFD DETALLADO / OpenFOAM — campos 3D y cargas proceden únicamente de VTK y fuerzas exportados.",
                name="cfd-result", position="lower_left", font_size=9, color="#17212b",
            )
            # Keep the engineering camera focused on the vehicle instead of
            # fitting the entire 11 m tunnel and making the rocket disappear.
            self.set_camera_preset("isometric")
            self.set_cfd_frame(0, force=True)
        except Exception as exc:
            self._plotter.add_text(
                f"No se pudo mostrar el VTK de OpenFOAM: {exc}", name="cfd-result",
                position="lower_left", font_size=9, color="#8b3a1d",
            )
        self._render_scene()
